import type { SymbolData } from './types'

export const ALL_SYMBOLS_DATA: SymbolData[] = [
  { symbol: 'ETH', lighterMarketId: 0 },
  { symbol: 'BTC', lighterMarketId: 1 },
  { symbol: 'SOL', lighterMarketId: 2 },
  { symbol: 'DOGE', lighterMarketId: 3 },
  { symbol: '1000PEPE', lighterMarketId: 4 },
  { symbol: 'WIF', lighterMarketId: 5 },
  { symbol: 'WLD', lighterMarketId: 6 },
  { symbol: 'XRP', lighterMarketId: 7 },
  { symbol: 'LINK', lighterMarketId: 8 },
  { symbol: 'AVAX', lighterMarketId: 9 },
  { symbol: 'NEAR', lighterMarketId: 10 },
  { symbol: 'DOT', lighterMarketId: 11 },
  { symbol: 'TON', lighterMarketId: 12 },
  { symbol: 'TAO', lighterMarketId: 13 },
  { symbol: 'POL', lighterMarketId: 14 },
  { symbol: 'TRUMP', lighterMarketId: 15 },
  { symbol: 'SUI', lighterMarketId: 16 },
  { symbol: '1000SHIB', lighterMarketId: 17 },
  { symbol: '1000BONK', lighterMarketId: 18 },
  { symbol: '1000FLOKI', lighterMarketId: 19 },
  { symbol: 'BERA', lighterMarketId: 20 },
  { symbol: 'FARTCOIN', lighterMarketId: 21 },
  { symbol: 'AI16Z', lighterMarketId: 22 },
  { symbol: 'POPCAT', lighterMarketId: 23 },
  { symbol: 'HYPE', lighterMarketId: 24 },
  { symbol: 'BNB', lighterMarketId: 25 },
  { symbol: 'JUP', lighterMarketId: 26 },
  { symbol: 'AAVE', lighterMarketId: 27 },
  { symbol: 'MKR', lighterMarketId: 28 },
  { symbol: 'ENA', lighterMarketId: 29 },
  { symbol: 'UNI', lighterMarketId: 30 },
  { symbol: 'APT', lighterMarketId: 31 },
  { symbol: 'SEI', lighterMarketId: 32 },
  { symbol: 'KAITO', lighterMarketId: 33 },
  { symbol: 'IP', lighterMarketId: 34 },
  { symbol: 'LTC', lighterMarketId: 35 },
  { symbol: 'CRV', lighterMarketId: 36 },
  { symbol: 'PENDLE', lighterMarketId: 37 },
  { symbol: 'ONDO', lighterMarketId: 38 },
  { symbol: 'ADA', lighterMarketId: 39 },
  { symbol: 'S', lighterMarketId: 40 },
  { symbol: 'VIRTUAL', lighterMarketId: 41 },
  { symbol: 'SPX', lighterMarketId: 42 },
  { symbol: 'TRX', lighterMarketId: 43 },
  { symbol: 'SYRUP', lighterMarketId: 44 },
  { symbol: 'PUMP', lighterMarketId: 45 },
  { symbol: 'LDO', lighterMarketId: 46 },
  { symbol: 'PENGU', lighterMarketId: 47 },
  { symbol: 'PAXG', lighterMarketId: 48 },
  { symbol: 'EIGEN', lighterMarketId: 49 },
  { symbol: 'ARB', lighterMarketId: 50 },
  { symbol: 'RESOLV', lighterMarketId: 51 },
  { symbol: 'GRASS', lighterMarketId: 52 },
  { symbol: 'ZORA', lighterMarketId: 53 },
  { symbol: 'LAUNCHCOIN', lighterMarketId: 54 },
  { symbol: 'OP', lighterMarketId: 55 },
  { symbol: 'ZK', lighterMarketId: 56 },
  { symbol: 'PROVE', lighterMarketId: 57 },
  { symbol: 'BCH', lighterMarketId: 58 },
  { symbol: 'HBAR', lighterMarketId: 59 },
  { symbol: 'ZRO', lighterMarketId: 60 },
  { symbol: 'GMX', lighterMarketId: 61 },
  { symbol: 'DYDX', lighterMarketId: 62 },
  { symbol: 'MNT', lighterMarketId: 63 },
  { symbol: 'ETHFI', lighterMarketId: 64 },
  { symbol: 'AERO', lighterMarketId: 65 },
  { symbol: 'USELESS', lighterMarketId: 66 },
  { symbol: 'TIA', lighterMarketId: 67 },
  { symbol: 'MORPHO', lighterMarketId: 68 },
  { symbol: 'VVV', lighterMarketId: 69 },
  { symbol: 'YZY', lighterMarketId: 70 },
  { symbol: 'XPL', lighterMarketId: 71 },
  { symbol: 'WLFI', lighterMarketId: 72 },
  { symbol: 'CRO', lighterMarketId: 73 },
  { symbol: 'NMR', lighterMarketId: 74 },
  { symbol: 'DOLO', lighterMarketId: 75 },
  { symbol: 'LINEA', lighterMarketId: 76 },
  { symbol: 'XMR', lighterMarketId: 77 },
  { symbol: 'PYTH', lighterMarketId: 78 },
  { symbol: 'SKY', lighterMarketId: 79 },
  { symbol: 'MYX', lighterMarketId: 80 },
  { symbol: '1000TOSHI', lighterMarketId: 81 },
  { symbol: 'AVNT', lighterMarketId: 82 },
  { symbol: 'ASTER', lighterMarketId: 83 },
  { symbol: '0G', lighterMarketId: 84 },
  { symbol: 'STBL', lighterMarketId: 85 },
  { symbol: 'APEX', lighterMarketId: 86 },
  { symbol: 'FF', lighterMarketId: 87 },
  { symbol: '2Z', lighterMarketId: 88 },
  { symbol: 'EDEN', lighterMarketId: 89 },
  { symbol: 'ZEC', lighterMarketId: 90 },
  { symbol: 'MON', lighterMarketId: 91 },
  { symbol: 'XAU', lighterMarketId: 92 },
  { symbol: 'XAG', lighterMarketId: 93 },
  { symbol: 'MEGA', lighterMarketId: 94 },
  { symbol: 'MET', lighterMarketId: 95 },
  { symbol: 'EURUSD', lighterMarketId: 96 },
  { symbol: 'GBPUSD', lighterMarketId: 97 },
  { symbol: 'USDJPY', lighterMarketId: 98 },
  { symbol: 'USDCHF', lighterMarketId: 99 },
  { symbol: 'USDCAD', lighterMarketId: 100 },
  { symbol: 'CC', lighterMarketId: 101 },
  { symbol: 'ICP', lighterMarketId: 102 },
  { symbol: 'FIL', lighterMarketId: 103 },
  { symbol: 'STRK', lighterMarketId: 104 },
  { symbol: 'USDKRW', lighterMarketId: 105 },
  { symbol: 'AUDUSD', lighterMarketId: 106 },
  { symbol: 'NZDUSD', lighterMarketId: 107 },
  { symbol: 'HOOD', lighterMarketId: 108 },
  { symbol: 'COIN', lighterMarketId: 109 },
  { symbol: 'NVDA', lighterMarketId: 110 },
  { symbol: 'PLTR', lighterMarketId: 111 },
  { symbol: 'TSLA', lighterMarketId: 112 },
  { symbol: 'AAPL', lighterMarketId: 113 },
  { symbol: 'AMZN', lighterMarketId: 114 },
  { symbol: 'MSFT', lighterMarketId: 115 },
  { symbol: 'GOOGL', lighterMarketId: 116 },
  { symbol: 'META', lighterMarketId: 117 },
]

export const ALL_SYMBOLS = ALL_SYMBOLS_DATA.map((item) => item.symbol)

export const SYMBOL_MARKET_ID_MAP = ALL_SYMBOLS_DATA.reduce(
  (acc, item) => {
    acc[item.symbol] = item.lighterMarketId
    return acc
  },
  {} as Record<string, number>
)

export const MARKET_ID_TO_SYMBOL = Object.fromEntries(
  Object.entries(SYMBOL_MARKET_ID_MAP).map(([k, v]) => [v, k])
) as Record<number, string>

export const DEFAULT_WATCHED_SYMBOLS = ['ETH', 'BTC', 'SOL', 'HYPE', 'BNB']

