import { useState, useEffect } from 'react'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  return (
    <main className="text-center p-4 mx-auto">
      <h3 className="text-primary uppercase text-2xl font-extralight leading-tight my-8">
        Popup Page
      </h3>
      <div className="flex justify-center items-center my-8">
        <button
          onClick={minus}
          disabled={count <= 0}
          className="text-base px-4 py-2 border border-primary rounded bg-transparent text-primary cursor-pointer w-12 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          -
        </button>
        <label className="text-2xl mx-4">{count}</label>
        <button
          onClick={add}
          className="text-base px-4 py-2 border border-primary rounded bg-transparent text-primary cursor-pointer w-12"
        >
          +
        </button>
      </div>
      <a
        href={link}
        target="_blank"
        className="text-xs text-[#cccccc] no-underline hover:text-primary"
      >
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
