import { useEffect, useState } from 'react'

export const Options = () => {
  const [countSync, setCountSync] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCountSync(result.count || 0)
    })

    chrome.runtime.onMessage.addListener((request) => {
      if (request.type === 'COUNT') {
        setCountSync(request.count || 0)
      }
    })
  }, [])

  return (
    <main className="text-center p-4 mx-auto">
      <h3 className="text-primary uppercase text-2xl font-extralight leading-tight my-8">
        Options Page
      </h3>
      <h4 className="text-lg">Count from Popup: {countSync}</h4>
      <a
        href={link}
        target="_blank"
        className="text-xs text-[#cccccc] no-underline hover:text-primary"
      >
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Options
