export const DevTools = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  return (
    <main className="text-center p-4 mx-auto">
      <h3 className="text-primary uppercase text-2xl font-extralight leading-tight my-8">
        DevTools Page
      </h3>
      <a
        href={link}
        target="_blank"
        className="text-xs text-[#cccccc] no-underline hover:text-primary"
      >
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default DevTools
