import { useState, useEffect } from 'react'

export const NewTab = () => {
  const getTime = () => {
    const date = new Date()
    const hour = String(date.getHours()).padStart(2, '0')
    const minute = String(date.getMinutes()).padStart(2, '0')
    return `${hour}:${minute}`
  }

  const [time, setTime] = useState(getTime())
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  useEffect(() => {
    let intervalId = setInterval(() => {
      setTime(getTime())
    }, 1000)

    return () => {
      clearInterval(intervalId)
    }
  }, [])

  return (
    <section className="w-screen h-screen flex flex-col justify-between items-center relative before:content-[''] before:fixed before:-z-10 before:w-screen before:h-screen before:bg-[url('https://source.unsplash.com/random')] before:bg-cover before:blur-[10px]">
      <span></span>
      <h1 className="text-primary uppercase text-7xl my-8">{time}</h1>
      <a
        href={link}
        target="_blank"
        className="text-xs text-[#cccccc] no-underline mb-2"
      >
        generated by create-chrome-ext
      </a>
    </section>
  )
}

export default NewTab
